version: "3.3"

services:
  frontend:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
      args:
        - REACT_APP_API_URL=${API_URL}
        - REACT_APP_WS_URL=${WS_URL}      
    depends_on:
      - backend
    ports:
      - "80:80"
  
  backend:
    build:
      context: ./backend
    command: python3 main.py
    environment:
      - REDIS_URL=${REDIS_URL}
    ports:
      - "8000:8000"
    depends_on:
      - cache
    volumes:
    - ./backend:/home/app
  
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

volumes:
  db-data:
  